my_snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: pg13792.us-east4.gcp
      user: Tonzu
      password: Snowflake@091287
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: BIG_DATA
      schema: BD1
      threads: 8
