create or replace TABLE RAW.PUBLIC.EMPLOYEE_airflow_dock (
	ID NUMBER(38,0) NOT NULL autoincrement,
	NAME VARCHAR(50) NOT NULL,
	DEPARTMENT VARCHAR(50) NOT NULL,
	SALARY NUMBER(10,2) NOT NULL,
	HIRE_DATE DATE NOT NULL,
	primary key (ID)
);